// define vars
var mongoose = require('mongoose'),
    Schema   = mongoose.Schema,

    // define model schema
    schema   = new mongoose.Schema({

        /**
         * short id generated by /utils/generateID.js
         * @type {String}
         */
        id:           String,

        /**
         * timestamp of creation date
         * @type {Date}
         */
        timestamp:    { 'type': Date,   'default': Date.now },

        /**
         * testcase name
         * @type {String}
         */
        name:         String,

        /**
         * start URL
         * @type {String}
         */
        url:          String,

        /**
         * testcase cookie preset
         * @type {key-value list}
         */
        cookies:      Array,

        /**
         * resolution the testcase has to be run with (width x height)
         * @type {Array}
         */
        resolution:   [Number,Number],

        /**
         * list of taken screenshot during the testrun
         * @type {Array}
         */
        screenshots: [{

            /**
             * path of screenshot
             * @type {String}
             */
            path:     String,

            /**
             * url of website
             * @type {String}
             */
            url:      String
        }],

        /**
         * tasks the user has to solve
         * @type {Array}
         */
        tasks:        [{type: Schema.ObjectId, ref: 'Task'}]
    });

/**
 * set attributes by given object
 * @param  {Object} obj  object with model attributes
 */
schema.methods.setAttributes = function(obj) {
    this.name       = obj.name;
    this.url        = obj.url;
    this.cookies    = obj.cookies;
    this.resolution = obj.resolution;
};

// export model
exports.model = mongoose.model('TestCase',schema);